### ISSUE TITLE
Glyphs for composing other glyphs

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#114]
Hi Richard,

These glyphs were in the original default and were drawn, and will be used, to compose other glyphs across the design space.

Please re-introduce and reconcile from the list below for these six styles, and beyond:

- Amstelvar-Roman.ufo
- Amstelvar-Roman-opsz-min.ufo
- Amstelvar-Roman-opsz-max.ufo
- Amstelvar-Italic.ufo
- Amstelvar-Italic-opsz-min.ufo
- Amstelvar-Italic-opsz-max.ufo

Uhookabove
apostrophemod
commercialMinusSign
diagonalbarO
diagonalbarl
diagonalbaro
doubleprimemod
engn
engtail
horizontalbar
horizontalbarH
horizontalbarlc
hornU
hornu
hyphentwo
idotaccent
leftanglebracket
primemod
rightanglebracket
uhookabove

**Comment by dberlow** [comment]
Richard,

Don't actually do anything about this it's my job now.

The main advantage of getting the glyph repertoire settled and complete in
the Roman was to do so before we went off and expanded the family
That advantage is now lost and I will have to go backwards and straighten
it out.

It was not and is not Richard's job.

Jill,

Where is the glyph repertoire sheet I asked for please.

**Comment by richardlipton** [comment]
I actually did add those glyphs back into the Roman default but have not synched it.
Let me know if you want me to rename it Amstelvar-Roman.RL and sync or just let you
straighten it out your way.

**Comment by pichotta** [comment]
In trying to reconstruct this history.

Character Set = Glyph Repertoire = Client spec = Unicode values

vs.

Glyphs = Build Set = Glyphs drawn = some glyphs non-Unicode used to compose other glyphs

The Glyph Repertoire is what we are delivering to Google, and that the Build Set is what we need in order to fulfill the Latin 600 set.


from the README:
March 15, 2019 FB's SO completed Amstelvar-Roman.ufo according to CharacterSet.txt

I think the trouble is that the Amstelvar-NewCharset set (based on GF Latin Plus) deleted glyphs from the Build Set posted above such as: diagonalbarO, diagonalbarl, diagonalbar, engn, engtail

**Comment by dberlow** [comment]
Jill, Richard,

Just remember the simple parts
     not to delete glyphs from a variable font someone is working with alongside you, and... 
     sometimes in Vars it’s easier to add glyphs to the repertoire to make some composites, even thought those glyphs are not in the client’s repertoire.

I will handle all of the glyphs that are not drawn to stand alone, like the bar of the O, and all of the composites that need to be made from these glyphs, like O-bar. 

After I check all of the glyphs, I will remark the Amstelvar repertoire for which glyphs need to be drawn by Richard and continue to micromanage this on this repo.

Jill if you have any further questions on this project, regarding anything, please email me directly and let’s leave this repo to clear instructions and goals between SO, RL and myself.

Thanks.




On Apr 10, 2019, at 4:40 PM, pichotta <notifications@github.com> wrote:

In trying to reconstruct this history.

Character Set = Glyph Repertoire = Client spec = Unicode values

vs.

Glyphs = Build Set = Glyphs drawn = some glyphs non-Unicode used to compose other glyphs

The Glyph Repertoire is what we are delivering to Google, and that the Build Set is what we need in order to fulfill the Latin 600 set.

from the README:
March 15, 2019 FB's SO completed Amstelvar-Roman.ufo according to CharacterSet.txt

I think the trouble is that the Amstelvar-NewCharset set (based on GF Latin Plus) deleted glyphs from the Build Set posted above such as: diagonalbarO, diagonalbarl, diagonalbar, engn, engtail

**Comment by dberlow** [comment]
Santiago is reconciling this over the weekend.

**Comment by sannorozco** [comment]
Reconciled Glyph build Set on Roman:

Amstelvar-Roman.ufo
Amstelvar-Roman-opsz-min.ufo
Amstelvar-Roman-opsz-max.ufo
Amstelvar-Roman-wghtmin.ufo
Amstelvar-Roman-wghtmax.ufo
Amstelvar-Roman-wdthmin.ufo
Amstelvar-Roman-wdthmax.ufo

Glyphs Added: 
Uhookabove
apostrophemod
commercialMinusSign
diagonalbarO
diagonalbarl
diagonalbaro
doubleprimemod
engn
engtail
horizontalbar
horizontalbarH
horizontalbarlc
hornU
hornu
hyphentwo
idotaccent
leftanglebracket
primemod
rightanglebracket
uhookabove

Glyphs modified: ƯÐĐĦŁŊØŦẞđħłŋøŧ

Italics pending.

**Comment by dberlow** [comment]
I Updated:
Amstelvar-Roman-XTRAmin
Amstelvar-Roman-XTRAmax
Amstelvar-Roman-YOPQmin
Amstelvar-Roman-YOPQmax
Amstelvar-Roman-XOPQmin
Amstelvar-Roman-YOPQmax

**Comment by dberlow** [comment]
It sure is confusing this way.

Where is the glyph repertoire sheet I asked for please?

**Comment by pichotta** [comment]
Amstelvar —  Axes + Build + Latin Pro 600

https://docs.google.com/spreadsheets/d/1EZ6nu8wDf1q3_F4Rabbn0bBvpqG41On4LcoBH0Y8EEI/edit?usp=sharing

**Comment by dberlow** [comment]
Thanks. But because the sort is not respectful of the process it's not easy
to use.

Is there some way we can sort this according to something other than Glyph
order?

Also, are the marks of what's done coming in from the ufo?
