### ISSUE TITLE
May 20 status

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#129]
Amstelvar works

Delivery of prototype ascii registered axis? SO, CJ?
Quote for kerning Regular? DW, JP?

Drawing of Roman Latin-1 registered axes done- to QA?

DW kerning Roman Regula rLatin-1 

Richard working in Italic controls, for 4 non-Regular styles. 
(wght and wdth min and max)

DB working on completing  Roman Latin-1 xopq and yopq and xtra.

**Comment by pichotta** [comment]
Hi Dyana,

> On May 20, 2019, at 11:11 AM, David Berlow <notifications@github.com> wrote:
> 
> Delivery of prototype ascii registered axis? SO, CJ?
> Quote for kerning Regular? DW, JP
> 
Do you have a quote for kerning the Amstelvar Regular?  

Remember that DB would like you to kern the heck out of it with all possible combinations.
But, it would be good to verify with him the extent because the number of pairs would effect file size.

There are about 480 glyphs that could receive kerning.  How many hours do you think it will realistic take to kern, proof, and fix?

**Comment by richardlipton** [comment]
The Italic controls for wght and wdth min and max were nudged about and I continued on to complete the caps and lowercase for all four styles. Compatibilized and synched.

**Comment by xxdgwxx** [comment]
I'm pretty close to finishing the kerning, just need to do the figs to figs, figs to sorts, Vietnamese characters, and then proof. I expect to finish tomorrow. 

Currently, there are 1945 pairs with 98 groups. 

How does $2500 work for everyone?

**Comment by dberlow** [comment]
Sounds great.

Closed quote.
