### ISSUE TITLE
Compatibility report on new ij ij acute added glyphs

### ISSUE THREAD

**Issue by sannorozco** [TypeNetwork/Amstelvar#136]
There were some compatibility issues in the latest build.

Roman:
WARNING:fontTools.varLib:glyph ijacute has incompatible masters; skipping

Italic:
WARNING:fontTools.varLib:glyph Iacute_J.loclNLD has incompatible masters; skipping
WARNING:fontTools.varLib:glyph iacute_j.loclNLD has incompatible masters; skipping
WARNING:fontTools.varLib:glyph Jacute.loclNLD has incompatible masters; skipping
WARNING:fontTools.varLib:glyph jacute.loclNLD has incompatible masters; skipping

These I assume are because it haven’t been modified on the other masters:
WARNING:fontTools.varLib:glyph B has incompatible masters; skipping
WARNING:fontTools.varLib:glyph E has incompatible masters; skipping
WARNING:fontTools.varLib:glyph F has incompatible masters; skipping
WARNING:fontTools.varLib:glyph J has incompatible masters; skipping
WARNING:fontTools.varLib:glyph K has incompatible masters; skipping
WARNING:fontTools.varLib:glyph P has incompatible masters; skipping
WARNING:fontTools.varLib:glyph R has incompatible masters; skipping
WARNING:fontTools.varLib:glyph S has incompatible masters; skipping
WARNING:fontTools.varLib:glyph V has incompatible masters; skipping
WARNING:fontTools.varLib:glyph W has incompatible masters; skipping
WARNING:fontTools.varLib:glyph Z has incompatible masters; skipping
WARNING:fontTools.varLib:glyph d has incompatible masters; skipping
WARNING:fontTools.varLib:glyph g has incompatible masters; skipping
WARNING:fontTools.varLib:glyph h has incompatible masters; skipping
WARNING:fontTools.varLib:glyph q has incompatible masters; skipping
WARNING:fontTools.varLib:glyph r has incompatible masters; skipping
WARNING:fontTools.varLib:glyph w has incompatible masters; skipping
WARNING:fontTools.varLib:glyph y has incompatible masters; skipping

There are more, but I assume it’s because aren’t touched yet.

**Comment by dberlow** [comment]
I am working now on yopq.

 I got a message that those glyphs that you mention were out of sync and I have gotten them synced while I was working.

On May 29, 2019, at 10:45 AM, Santiago Orozco <notifications@github.com> wrote:

There were some compatibility issues in the latest build.

Roman:
WARNING:fontTools.varLib:glyph ijacute has incompatible masters; skipping

Italic:
WARNING:fontTools.varLib:glyph Iacute_J.loclNLD has incompatible masters; skipping
WARNING:fontTools.varLib:glyph iacute_j.loclNLD has incompatible masters; skipping
WARNING:fontTools.varLib:glyph Jacute.loclNLD has incompatible masters; skipping
WARNING:fontTools.varLib:glyph jacute.loclNLD has incompatible masters; skipping

These I assume are because it haven’t been modified on the other masters:
WARNING:fontTools.varLib:glyph B has incompatible masters; skipping
WARNING:fontTools.varLib:glyph E has incompatible masters; skipping
WARNING:fontTools.varLib:glyph F has incompatible masters; skipping
WARNING:fontTools.varLib:glyph J has incompatible masters; skipping
WARNING:fontTools.varLib:glyph K has incompatible masters; skipping
WARNING:fontTools.varLib:glyph P has incompatible masters; skipping
WARNING:fontTools.varLib:glyph R has incompatible masters; skipping
WARNING:fontTools.varLib:glyph S has incompatible masters; skipping
WARNING:fontTools.varLib:glyph V has incompatible masters; skipping
WARNING:fontTools.varLib:glyph W has incompatible masters; skipping
WARNING:fontTools.varLib:glyph Z has incompatible masters; skipping
WARNING:fontTools.varLib:glyph d has incompatible masters; skipping
WARNING:fontTools.varLib:glyph g has incompatible masters; skipping
WARNING:fontTools.varLib:glyph h has incompatible masters; skipping
WARNING:fontTools.varLib:glyph q has incompatible masters; skipping
WARNING:fontTools.varLib:glyph r has incompatible masters; skipping
WARNING:fontTools.varLib:glyph w has incompatible masters; skipping
WARNING:fontTools.varLib:glyph y has incompatible masters; skipping

There are more, but I assume it’s because aren’t touched yet.

**Comment by sannorozco** [comment]
Yes, if they’re different from the ones you’re working on YOPQ, there shouldn’t be a problem.

It might be necessary to add them to all masters.

**Comment by dberlow** [comment]
I have to be doing a contour compatibility test at the end on my yopqing and I will make sure to use the latest regular for comparison.

On May 29, 2019, at 10:59 AM, Santiago Orozco <notifications@github.com> wrote:

Yes, if they’re different from the ones you’re working on YOPQ, there shouldn’t be a problem.

It might be necessary to add them to all masters.

**Comment by djrrb** [comment]
just fyi letting y'all know that i made ijacute into components in a couple masters in order to make the dollar-sign-changing fonts generate correctly

**Comment by sannorozco** [comment]
Merged into master, working on now.
