### ISSUE TITLE
A Build without gvar duplication

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Amstelvar#150]
The current construction of Amstelvar makes axes appear "expensive" (in bytes) because the gvar data associated with them is duplicative, due to the current OpenType specification.

Please make an "Amstelvar 2" build path that does no duplication, and therefore only works when precisely coordinated (using JS.)

I guess that means, no opsz, wght, wdth or GRAD, and no Primary Y Transparency YTRA, since that can be done by selecting all the axes in the Y Transparency bundle?

**Comment by dberlow** [comment]
There is such a build of AmstelvarAlpha (-parametric only). I will find it shortly. In order to use it for this purpose, I’d need to add a spacing axes, overshoot axes and ink trap/diagonal taper axes, or skip the latter two?

The new Amstelvar’s spec is for a safe user space. The y-trans are all going to be the same as in alpha, but grad, yopq, xopq and xtra are all intended to be tailored, via instances today, avar2 tomorrow, to provide appropriately useful but safe ranges for each of those four parametric axes, as they effect the registered axes.

Additionally, the new Amstelvar has opsz intermediates between the default and max, bending the effects for now, also awaiting more effective description with avar2. I do not k so how to simulate the bend in .js, yet... but I’ll think about it.

In 5 weeks, we should have a completed Roman design space, bent and tailored without avar2, but highly informative and useful for testing avar2 compression as soon as the next tools develops. 

Y-transparencies will not be avar2 compressed, but opsz, and the tailoring of all the  grad, yopq, xopq and xtra ranges, via new and weightless intermediates and end capping instances, will go smoothly.

Let me know how quickly you need to proceed... after my nap.


On Jul 7, 2019, at 10:44 AM, Dave Crossland <notifications@github.com> wrote:

The current construction of Amstelvar makes axes appear "expensive" (in bytes) because the gvar data associated with them is duplicative, due to the current OpenType specification.

Please make an "Amstelvar 2" build path that does no duplication, and therefore only works when precisely coordinated (using JS.)

I guess that means, no opsz, wght, wdth or GRAD, and no Primary Y Transparency YTRA, since that can be done by selecting all the axes in the Y Transparency bundle?

**Comment by dberlow** [comment]
There’s this:
https://github.com/TypeNetwork/Amstelvar/tree/master/fonts/old/old/3%20Different%20Amstelvar-VFs
Containing:
Amstelvar-Roman-parametric-VF  274k (11 parametric axes)
Amstelvar-Roman-VF 543k (15 axes total – 11 parametric and 4 blended)
Amstelvar-Roman-blended-VF  206 k (just blended axes; opsz, GRAD, wght, wdth)

These were made before we changed the names of this run to "Alpha", before the crit, and etc.

I'll ask the location of the .js from Chris, (it is the same data that moves the sliders, I think — it's been posted before.)

**Comment by davelab6** [comment]
> In order to use it for this purpose, I’d need to add a spacing axes, overshoot axes and ink trap/diagonal taper axes, or skip the latter two?

Not very quick, but I would like the current development with on Amstelvar to have the axes you mentioned

**Comment by davelab6** [comment]
To close your issue, I'd like the build path included in the CI output
