### ISSUE TITLE
qa — UPM and overshoot

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Amstelvar#50]
**UPM**
Confirming that the UPM should be 2000 vs. 2048?

**Asc/Desc**
and, that the CapHt should sit on the Ascender value of 1500 (vs. 1568 in Ital)?
 that the overshoot of the cap rounds should extend above 20 units?

Roman.ufo Ascender = 1500  (H @ 1500, O overshoot at 1520)
Italic.ufo Ascender = 1568 (H @ 150,  O overshoot at 1526)

Typically the overshoot is accommodated by the Asc value so maybe 1568/-448 is to be the default?

**Comment by dberlow** [comment]
Upm is correct, Amstelvar has been on a 2000 units since it was created.
 David announced to the entire design staff that he was shifting to 2000 units for new designs and that was four years ago.

**Comment by dberlow** [comment]
Em is how I start all new families... since 2012.

The values I am tracking in the font info of the various styles, are the values that matter for variations. Merely tracking the extents, does not help.

Also, setting those font values in the final var, and in the instances produced by that var, use a different method, one stored in the MVAR table.

Look it up, please.

**Comment by pichotta** [comment]
I see this MVAR post and links now. Thank you  http://typedrawers.com/discussion/comment/33932
