### ISSUE TITLE
Review: opsz min and max

### ISSUE THREAD

**Issue by sberlow** [TypeNetwork/Amstelvar#65]
Let me know when these are ready for review by client.
I will have them formatted and presented
thanks

**Comment by dberlow** [comment]
Now, as far as I know.

I’m also pretty finished with all regular opsz. jill has them.  I would very much like to know they are done get a regular back for a template. 

 In the meantime regular ytlc, ytuc, ytde and ytas will be done thurs.

**Comment by dberlow** [comment]
Also, please remember that whatever rush people might BN, the optical size axis needs, I repeat needs intermediates between the default and 0PSZ Max.

Let me know when Jill, DJR and I can get together and I can get the font make tool, because I’m cycling the design faster than the expected making of variable fonts, which I’d hope to have started last week with whatever grist I was providing.

I’ve now been through a cycle of correcting those three opsz masters again because there were lots of missed directed accents because of the script that is no longer being used, I think. 

Thanks.

**Comment by djrrb** [comment]
I have not yet implemented an `opsz` intermediate. 

I was looking into `avar` implementations mapping 36pt to 72pt see if this would be better than adding new poles. Assigning this issue to myself.

**Comment by djrrb** [comment]
Commit 574b3efdf3b61821ba7d658136db11137fd043d1 has an `avar` table where opsz 36 is pinned to what would have been 72. This is my first time using `avar` and I do seem to be getting slightly different results (see attached image), but I haven’t fully tested.

<img width="601" alt="screen shot 2018-04-27 at 2 07 00 pm" src="https://user-images.githubusercontent.com/6578861/39398329-2491e56e-4ada-11e8-86d3-18a316dc5901.png">

**Comment by sberlow** [comment]
@davelab6 
PDF and Keynote files for your review of the Roman and Italic.

https://github.com/TypeNetwork/Amstelvar/tree/master/docs/2018-05-05%20opsz%20max%20and%20min%20

**Comment by sberlow** [comment]
@davelab6

**Comment by davelab6** [comment]
As stated in https://github.com/TypeNetwork/Amstelvar/issues/81#issuecomment-395903958 I will post feedback on this here soon, so assigning to me. 

Note to self: https://github.com/TypeNetwork/Amstelvar/issues/52 is a child issue of this

**Comment by davelab6** [comment]
I printed the PDFs same links to above, marked them up with a red pen over a few sessions, scanned the paper, and PR'd the scanned PDF here, https://github.com/TypeNetwork/Amstelvar/pull/94

Next steps are for @dberlow to try and decipher what I scribbled, and for me to provide typed up comments that refer to that PDF :)
