### ISSUE TITLE
Upm 4000?

### ISSUE THREAD

**Issue by davelab6** [TypeNetwork/Amstelvar#79]
https://mobile.twitter.com/Tosche_E/status/1000013198156877826

Especially for the italics, I wonder that toshi is right that rounding errors can be mitigated by a higher upm. 

Perhaps there are filesize implications although my guess is woff2 will squirrel them away

**Comment by davelab6** [comment]
This seems general, not typeface specific... So, some specific questions from me for David: 

The current UPM is 2000?

Which glyphs/axes will typically exhibit rounding errors?

Are there any rounding errors visible in the current builds?

**Comment by dberlow** [comment]
Whoa there. This issue points to a twitter thread that points to an Instagram movie of a P taking a journey through what looks like an xtra range.

Someone asks how this works with diagonals, which is like out of nowhere, and then all kinds of kinky talk breaks out.

So there are a bunch of issues bundled up in that social media thread. 
In general, kinks form because the three points that formed a straight line in the masters are unable to do so in an instance because the x and y deltas that have been applied, prevent a straight line through the three points form being possible. 

Yes, the current upm is 2000. 

Can you give me an example of what a rounding error is in this context?

I’ll then look.
