### ISSUE TITLE
Proper design space

### ISSUE THREAD

**Issue by dberlow** [TypeNetwork/Amstelvar#89]
Primarily Chris...

It is clear to me from looking at the AmstelvarAlpha design space files, and the most recent Amstelvar design space files made by our process are not correct in the description of blended axes.

The error, in both cases mentioned above, is that the default font’s values have been kept for the parametric axes of the extremes in the blended axes, despite the fact that the parametric values of these extremes are different.

So, e.g the x transparency of opsz max is smaller that the x transparency of the default font, but this was never reflected in the parametric value of opsz max, xtra. That value was the same in the default, in the opsz min and in the opsz max. 

Of course this would make it impossible For anyone to write an interface to a variable font with parametric axes, where the sliders reflected the values of the instance a user was looking at, without writing a program to store the values from manual input and “fake” the movement of sliders. 

That is apparently what we did. 

Now, we have a font, the newest Amstelvar, that’s got all the correct values In the font and according to the OT spec. I hope it means we can throw out a bunch of useless code and make or typetools app conform to the spec and function according to our proposed and Developed framework.

Please only use this new font for software and content development. 

Please rearchitect any software based on looking at anything else other than the font’s axes for the correct values of any instance, and make uis that reflect the proper values from the font.

Thanks.

**Comment by chrissam42** [comment]
I take this to mean that the math has changed for how the parameters contribute to the composite axes? This has been done by @asaumierdemers just sending me the numbers and we store those externally to the font, as you surmised. Alexandre and I had tossed around the idea of storing those relationships in the font somehow so that they would always be up to date, but I don't think he ever figured out a way to pull that off. So if there are new numbers to put in, please let me know @asaumierdemers.

Anyway, the way typetools currently works, if you have adjusted one of the composite axes, is that the composite (e.g. `opsz`) is used as set and the contributing parametric axes are left at their defaults, even though their sliders move visually to indicate what the contributing values "would be" to get this result. (This is because I was informed that sometimes the composite axes are not simple algebraic combination of the parametrics, so you wouldn't get exactly the same results by just using parametric sliders.) If you then proceed to further tweak some parametric axes, then the composite one pops back to its default and the parametric slider values take over in the real CSS. It's complicated and ofteh buggy, but that's what is supposed to happen.

**Comment by dberlow** [comment]
I’m not saying that the math has changed. I am saying the process has been corrected, and the font now contains the right values for all parameter of all axes, and for all instances in the space, because they were valued correctly, where they wer not before.

And, all you should be doing with an app, when displaying what the blended axes are e.g., is showing what is in the axis data of the font at any instance the user slides to.

**Comment by chrissam42** [comment]
I interpret this to mean: keep doing the "slider ghosting" where adjusting a composite moves around the parametric sliders; but drop the trickery of maintaining some things at defaults behind the scenes, because it will now be happy if the CSS literally reflects all the adjusted parametric sliders along with the adjusted composite. Does that sound right?

Hoo boy is this stuff difficult to describe.

**Comment by dberlow** [comment]
Yes, but I I have to fix it and remanufacture for some bugs. So hold on.

Thanks.
